# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'stockMatch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'AFNetworking', '~> 3.2.1'
pod 'SDWebImage'
pod 'MJExtension'
  # Pods for stockMatch

  target 'stockMatchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'stockMatchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
